import {
  DashboardData,
  DashboardDataForPeriod,
  SlowLambdaData,
  SlowLambdaDataPoint,
  MostInvokedLambdaData,
  MostInvokedLambdaDataPoint,
  MostErrorsLambdaData,
  MostErrorsLambdaDataPoint,
  Tenant,
  Query,
  Totals,
  TotalsDataPoint,
  Mutation,
} from './schemas'

export default [
  'scalar JSON',
  MostInvokedLambdaData,
  SlowLambdaData,
  SlowLambdaDataPoint,
  MostInvokedLambdaDataPoint,
  MostErrorsLambdaDataPoint,
  MostErrorsLambdaData,
  DashboardData,
  DashboardDataForPeriod,
  TotalsDataPoint,
  Totals,
  Tenant,
  Query,
  Mutation,
]
