import {
  DynamoTypes,
  CostsData,
  CostsPerStackDataPoint,
  CostsPerServiceDataPoint,
  StackCostItem,
  ServiceCostItem,
  IntegrationData,
  Event,
  DashboardEventsData,
  OwnerData,
  Tenant,
  LambdaTypes,
  Query,
  Mutation,
} from './schemas'

export default [
  'scalar JSON',
  DynamoTypes,
  CostsData,
  CostsPerStackDataPoint,
  CostsPerServiceDataPoint,
  StackCostItem,
  ServiceCostItem,
  Event,
  DashboardEventsData,
  OwnerData,
  Tenant,
  LambdaTypes,
  IntegrationData,
  Query,
  Mutation,
]
